Sistema_Venta_Web/Controllers/GastosController.cs
using SVW.Entities;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading;
using System.Web;
using System.Web.Mvc;
using System.Xml.Linq;

namespace Sistema_Venta_Web.Controllers
{
    public class GastosController : Controller
    {

        public ActionResult Index()
        {
            return View();
        }

        public JsonResult GetGasto(Gastos obj)
        {
            var ctx = HttpContext.GetOwinContext();
            var tipoUsuario = ctx.Authentication.User.Claims.FirstOrDefault().Value;
            obj.Auditoria = new Auditoria
            {
                TipoUsuario = tipoUsuario
            };

            string draw = Request.Form.GetValues("draw")[0];
            int inicio = Convert.ToInt32(Request.Form.GetValues("start").FirstOrDefault());
            int fin = Convert.ToInt32(Request.Form.GetValues("length").FirstOrDefault());

            obj.Operacion = new Operacion
            {
                Inicio = (inicio / fin),
                Fin = fin
            };

            var bussingLogic = new SVW.BusinessLogic.BLGastos();
            var response = bussingLogic.GetGastos(obj);

            var Datos = response.Data;
            int totalRecords = Datos.Any() ? Datos.FirstOrDefault().Operacion.TotalRows : 0;
            int recFilter = totalRecords;

            var result = (new
            {
                draw = Convert.ToInt32(draw),
                recordsTotal = totalRecords,
                recordsFiltered = recFilter,
                data = Datos
            });

            return Json(result);
        }

        public JsonResult InsertUpdateGasto(Gastos obj)
        {
            var bussingLogic = new SVW.BusinessLogic.BLGastos();

            obj.Auditoria = new Auditoria
            {
                UsuarioCreacion = User.Identity.Name,
                UsuarioModificacion = User.Identity.Name
            };

            var response = bussingLogic.InsertUpdateGastos(obj);

            return Json(response);
        }

        public JsonResult DeleteGasto(Gastos obj)
        {
            var bussingLogic = new SVW.BusinessLogic.BLGastos();

            obj.Auditoria = new Auditoria
            {
                UsuarioModificacion = User.Identity.Name
            };

            var response = bussingLogic.DeleteGastos(obj);

            return Json(response);
        }

    }
}

Sistema_Venta_Web/Controllers/ProductoController.cs
using NPOI.HSSF.Util;
using NPOI.SS.UserModel;
using NPOI.SS.Util;
using NPOI.XSSF.UserModel;
using SVW.Entities;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;
using System.Xml.Linq;

namespace Sistema_Venta_Web.Controllers
{
    public class ProductoController : Controller
    {
        // GET: Producto
        public ActionResult Index()
        {
            return View();
        }

        public JsonResult GetProducto(Producto obj)
        {
            try
            {
                var ctx = HttpContext.GetOwinContext();
                var tipoUsuario = ctx.Authentication.User.Claims.FirstOrDefault().Value;
                obj.Auditoria = new Auditoria
                {
                    TipoUsuario = tipoUsuario
                };

                string draw = Request.Form.GetValues("draw")[0];
                int inicio = Convert.ToInt32(Request.Form.GetValues("start").FirstOrDefault());
                int fin = Convert.ToInt32(Request.Form.GetValues("length").FirstOrDefault());

                obj.    Operacion = new Operacion
                {
                    Inicio = (inicio / fin),
                    Fin = fin
                };

                var bussingLogic = new SVW.BusinessLogic.BLProducto();
                var response = bussingLogic.GetProducto(obj);

                var Datos = response.Data;
                var totalRecords = Datos.Any() ? Datos.Select(x => x.Operacion.TotalRows).FirstOrDefault() : 0;
                var recFilter = totalRecords;

                var result = (new
                {
                    draw = Convert.ToInt32(draw),
                    recordsTotal = totalRecords,
                    recordsFiltered = recFilter,
                    data = Datos
                });

                return Json(result);
            }
            catch (Exception ex)
            {
                return Json(SVW.Common.ConfigurationUtilities.ErrorCatchDataTable(ex));
            }
        }

        public JsonResult GetCategoria()
        {
            var bussingLogic = new SVW.BusinessLogic.BLProducto();

            var response = bussingLogic.GetCategoria();

            return Json(response);
        }

        public JsonResult InsertUpdateProducto(Producto obj)
        {
            var bussingLogic = new SVW.BusinessLogic.BLProducto();

            obj.Auditoria = new Auditoria
            {
                UsuarioCreacion = User.Identity.Name,
                UsuarioModificacion = User.Identity.Name
            };

            obj.Imagen = new Imagen
            {
                Imagen_Nombre = obj.Imagen.Imagen_Nombre,
                Imagen_Tipo = obj.Imagen.Imagen_Tipo,
                Imagen_ImgBase64 = obj.Imagen.Imagen_ImgBase64.Replace("data:"+
                obj.Imagen.Imagen_Tipo +";base64,", "")
            };

            var response = bussingLogic.InsertUpdateProducto(obj);

            return Json(response);
        }

        public JsonResult DeleteProducto(Producto obj)
        {
            var bussingLogic = new SVW.BusinessLogic.BLProducto();
            obj.Auditoria = new Auditoria
            {
                UsuarioModificacion = User.Identity.Name
            };
            var response = bussingLogic.DeleteProducto(obj);

            return Json(response);

        }

        public JsonResult GetAllProductos(Producto obj)
        {
            try
            {
                Session["ReporteProducto"] = null;
                var bussingLogic = new SVW.BusinessLogic.BLProducto();
                var response = bussingLogic.GetAllProductos(obj);
                Session["ReporteProducto"] = response.Data.ToList();
                return Json(response);
            }
            catch (Exception ex)
            {
                var result = new SVW.Common.Response<List<Producto>>(ex);
                return Json(result);
            }

        }

        public void GenerarExcel()
        {
            var NombreExcel = "Producto - Sistemas de Ventas ";

            // Recuperamos la data  de las consulta DB
            var data = (List<Producto>)Session["ReporteProducto"];

            // Creación del libro excel xlsx.
            var wb = new XSSFWorkbook();

            // Creación del la hoja y se especifica un nombre
            var fileName = WorkbookUtil.CreateSafeSheetName("Productos");
            ISheet sheet = wb.CreateSheet(fileName);

            // Contadores para filas y columnas.
            int rownum = 0;
            int cellnum = 0;

            // Creacion del estilo de la letra para las cabeceras.
            var fontCab = wb.CreateFont();
            fontCab.FontHeightInPoints = 10;
            fontCab.FontName = "Calibri";
            fontCab.Boldweight = (short)FontBoldWeight.Bold;
            fontCab.Color = HSSFColor.White.Index;

            // Creacion del color del estilo.
            var colorCab = new XSSFColor(new byte[] { 7, 105, 173 });

            // Se crea el estilo y se agrega el font al estilo
            var styleCab = (XSSFCellStyle)wb.CreateCellStyle();
            styleCab.SetFont(fontCab);
            styleCab.FillForegroundXSSFColor = colorCab;
            styleCab.FillPattern = FillPattern.SolidForeground;


            string[] Cabezeras = {
                    "Categoria", "Descripcion", "Precio", "Precio Mayor", "Cantidad", "Estado", "Fecha"
                };

            // Se crea la primera fila para las cabceras.
            IRow row = sheet.CreateRow(rownum++);
            ICell cell;

            foreach (var item in Cabezeras)
            {
                // Se crea celdas y se agrega las cabeceras
                cell = row.CreateCell(cellnum);
                cell.SetCellValue(item);
                cell.CellStyle = styleCab;
                cellnum++;
            }

            // Creacion del estilo de la letra para la data.
            var fontBody = wb.CreateFont();
            fontBody.FontHeightInPoints = 10;
            fontBody.FontName = "Arial";

            var styleBody = (XSSFCellStyle)wb.CreateCellStyle();
            styleBody.SetFont(fontBody);


            // Impresión de la data
            foreach (var item in data)
            {
                cellnum = 0;
                row = sheet.CreateRow(rownum++);
                
                AddValue(sheet, row, cellnum++, item.Categoria.Categoria_Nombre.ToString(), styleBody);
                AddValue(sheet, row, cellnum++, item.Producto_Nombre, styleBody);
                AddValue(sheet, row, cellnum++, item.Producto_Precio.ToString("F2"), styleBody);
                AddValue(sheet, row, cellnum++, item.Producto_Precio_Mayor.ToString("F2"), styleBody);
                AddValue(sheet, row, cellnum++, item.Producto_Cantidad.ToString(), styleBody);
                AddValue(sheet, row, cellnum++, item.Producto_Estado == 1 ? "Activo" : "Inactivo".ToString(), styleBody);
                AddValue(sheet, row, cellnum++, item.Producto_Fecha.ToString().Substring(6, 2) + "/" + item.Producto_Fecha.ToString().Substring(4, 2) + "/" + item.Producto_Fecha.ToString().Substring(0, 4), styleBody);
            }

            var nameFile = NombreExcel + DateTime.Now.ToString("dd_MM_yyyy HH:mm:ss") + ".xlsx";
            Response.AddHeader("content-disposition", "attachment; filename=" + nameFile);
            Response.ContentType = "application/octet-stream";
            Stream outStream = Response.OutputStream;
            wb.Write(outStream);
            outStream.Close();
            Response.End();
        }

        public void AddValue(ISheet sheet, IRow row, int cellnum, string value, ICellStyle styleBody)
        {
            ICell cell;
            cell = row.CreateCell(cellnum);
            cell.SetCellValue(value);
            cell.CellStyle = styleBody;
            sheet.AutoSizeColumn(cellnum);
        }
    }
}

Sistema_Venta_Web/Controllers/UsuarioController.cs
using SVW.Entities;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading;
using System.Web;
using System.Web.Mvc;
using System.Xml.Linq;

namespace Sistema_Venta_Web.Controllers
{
    public class UsuarioController : Controller
    {

        public ActionResult Index()
        {
            return View();
        }

        public JsonResult GetUsuario(Usuario obj)
        {
            var ctx = HttpContext.GetOwinContext();
            var tipoUsuario = ctx.Authentication.User.Claims.FirstOrDefault().Value;
            obj.Auditoria = new Auditoria
            {
                TipoUsuario = tipoUsuario
            };

            string draw = Request.Form.GetValues("draw")[0];
            int inicio = Convert.ToInt32(Request.Form.GetValues("start").FirstOrDefault());
            int fin = Convert.ToInt32(Request.Form.GetValues("length").FirstOrDefault());

            obj.Operacion = new Operacion
            {
                Inicio = (inicio / fin),
                Fin = fin
            };

            var bussingLogic = new SVW.BusinessLogic.BLUsuario();
            var response = bussingLogic.GetUsuario(obj);

            var Datos = response.Data;
            int totalRecords = Datos.Any() ? Datos.FirstOrDefault().Operacion.TotalRows : 0;
            int recFilter = totalRecords;

            var result = (new
            {
                draw = Convert.ToInt32(draw),
                recordsTotal = totalRecords,
                recordsFiltered = recFilter,
                data = Datos
            });

            return Json(result);
        }

        public JsonResult InsertUpdateUsuario(Usuario obj)
        {
            var bussingLogic = new SVW.BusinessLogic.BLUsuario();
            var response = bussingLogic.InsertUpdateUsuario(obj);

            return Json(response);
        }

        public JsonResult DeleteUsuario(Usuario obj)
        {
            var bussingLogic = new SVW.BusinessLogic.BLUsuario();
            var response = bussingLogic.DeleteUsuario(obj);

            return Json(response);
        }

    }
}

Sistema_Venta_Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" />
    <title>@ViewBag.Title - Sistema de Ventas</title>
    @*@Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")*@


    <link href="~/Content/lib/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/lib/font-awesome/css/font-awesome.min.css" rel="stylesheet" />
    <link href="~/Content/lib/jquery-ui/css/jquery-ui.min.css" rel="stylesheet" />
    <link href="~/Content/lib/ionicons/css/ionicons.min.css" rel="stylesheet" />
    <link href="~/Content/lib/dataTables/css/dataTables.bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/lib/dataTables/css/select.dataTables.min.css" rel="stylesheet" />
    <link href="~/Content/lib/select2/css/select2.min.css" rel="stylesheet" />
    <link href="~/Content/lib/bootstrap-datepicker/css/bootstrap-datepicker.min.css" rel="stylesheet" />

    <link href="~/Content/lib/adminLTE/css/adminLTE.min.css" rel="stylesheet" />
    <link href="~/Content/css/_all-skins.css" rel="stylesheet" />
    <link href="~/Content/css/main.css" rel="stylesheet" />


</head>
<body class="hold-transition skin-blue sidebar-mini">
    <div class="wrapper">
        <header class="main-header">
            <!-- Logo -->
            <a href="@Url.Action("Index", "Home")" class="logo">
                <!-- mini logo for sidebar mini 50x50 pixels -->
                <span class="logo-mini">
                    SV
                </span>
                <!-- logo for regular state and mobile devices -->
                <span class="logo-lg">
                    Sistema Ventas
                </span>
            </a>
            <!-- Header Navbar -->
            <nav class="navbar navbar-static-top" role="navigation">
                <!-- Sidebar toggle button-->
                <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
                    <span class="sr-only">Toggle navigation</span>
                </a>
                <!-- Application Name-->
                <div class="navbar-brand pull-left">
                    <label class="hidden-xs">
                        Inicio
                        <i class="fa fa-angle-right" aria-hidden="true"></i>
                        <small>@ViewBag.Title</small>
                    </label>
                </div>
                <!-- Navbar Right Menu -->
                <div class="navbar-custom-menu">
                    <ul class="nav navbar-nav">
                        <!-- User Account Menu -->
                        @{Html.RenderPartial("_LayoutMenuUserAccount");}
                    </ul>
                </div>
            </nav>
        </header>

        @if (User.Identity.IsAuthenticated)
        {
            <aside class="main-sidebar">
                <section class="sidebar" style="height:auto;">
                    <ul class="sidebar-menu" data-widget="tree">
                        <li class="header">MENU PRINCIPAL</li>
                        <li>
                            <a href="@Url.Action("Index", "Home")">
                                <i class="fa fa-th"></i> <span>Inicio</span>
                            </a>
                        </li>
                        <li>
                            <a href="@Url.Action("Index", "Producto")">
                                <i class="fa fa-fw fa-inbox"></i> <span>Producto</span>
                            </a>
                        </li>
                        <li>
                            <a href="@Url.Action("Index", "Ventas")">
                                <i class="ion ion-bag"></i> <span>Ventas</span>
                            </a>
                        </li>
						<li>
							<a href="@Url.Action("Index", "Gastos")">
								<i class="fa fa-money"></i> <span>Gastos</span>
							</a>
                        </li>
                        <li>
                            <a href="@Url.Action("Index", "Usuario")">
                                <i class="fa fa-user"></i> <span>Usuario</span>
                            </a>
                        </li>
                    </ul>

                </section>
            </aside>

        }
        else
        {
            <aside class="main-sidebar">
                <!-- sidebar: style can be found in sidebar.less -->
                <section class="sidebar" style="height:auto;">
                    <!-- Sidebar Menu -->
                    <ul class="sidebar-menu" data-widget="tree">
                        <li class="header">MENU PRINCIPAL</li>
                        <!-- Optionally, you can add icons to the links -->
                    </ul>
                </section>
            </aside>
        }




        <div class="content-wrapper" id="mainContent">
            @RenderBody()
        </div>

        <footer class="main-footer">
            <div class="pull-right hidden-xs">
                <label>@(string.Format("{0} {1}", "Sistema Ventas", "V1"))</label>
            </div>
            @*<label>@AppConfig.ApplicationCopyright</label>*@
        </footer>
    </div>

    @{ Html.RenderPartial("_LayoutModals"); }


    @*@Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")
        @RenderSection("scripts", required: false)*@

    <script src="~/Content/lib/jquery/js/jquery-3.3.1.min.js"></script>
    <script src="~/Content/lib/jquery/js/jquery.validate.min.js"></script>
    <script src="~/Content/lib/jquery/js/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/Content/lib/jquery-ui/js/jquery-ui-1.12.1.min.js"></script>
    <script src="~/Content/lib/bootstrap/js/bootstrap.min.js"></script>
    <script src="~/Content/lib/respond/js/respond.min.js"></script>
    <script src="~/Content/lib/select2/js/select2.full.min.js"></script>
    <script src="~/Content/lib/select2/js/es.js"></script>
    <script src="~/Content/lib/bootstrap-datepicker/js/bootstrap-datepicker.min.js"></script>
    <script src="~/Content/lib/bootstrap-datepicker/js/bootstrap-datepicker.es.min.js"></script>
    <script src="~/Content/lib/dataTables/js/jquery.dataTables.min.js"></script>
    <script src="~/Content/lib/dataTables/js/dataTables.bootstrap.min.js"></script>
    <script src="~/Content/lib/dataTables/js/dataTables.select.min.js"></script>
    <script src="~/Content/lib/fastclick/js/fastclick.js"></script>
    <script src="~/Content/lib/adminLTE/js/adminlte.js"></script>
    <script src="~/Content/lib/dataTables/js/buttons.html5.min.js"></script>
    <script src="~/Content/lib/dataTables/js/dataTables.buttons.min.js"></script>
    <script src="~/Content/lib/dataTables/js/jszip.min.js"></script>

    <script type="text/javascript">
            var baseSiteUrl = '@Url.Content("~/")';
    </script>
    <script src="~/Content/js/app.js"></script>
    @RenderSection("scripts", required: false)



</body>
</html>

Sistema_Venta_Web/Views/Shared/_LayoutMenuUserAccount.cshtml
@using Microsoft.AspNet.Identity

@if (User.Identity.IsAuthenticated)
{
    <li class="dropdown user user-menu">
        <!-- Menu Toggle Button -->
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <!-- The user image in the navbar-->
            <img src="~/Content/img/user-256.png" class="user-image" alt="User Image" />
            <!-- hidden-xs hides the username on small devices so only the image appears. -->
            <span class="hidden-xs">@User.Identity.GetUserName().ToUpper()</span>
        </a>
        <ul class="dropdown-menu">
            <!-- The user image in the menu -->
            <li class="user-header">
                <img src="~/Content/img/user-256.png" class="img-circle" alt="User Image" />
                <p>
                    <strong>@User.Identity.Name.ToUpper()</strong><br />
                    @if (User.Identity.GetUserId().Equals("1"))
                    {

                        <strong>Administrador  </strong>

                    }
                    else
                    {
                        <strong>Vendedor  </strong>
                    }
                </p>
            </li>
            <!-- Menu Body -->
            <li class="user-body">
                <div class="row">

                </div>
                <!-- /.row -->
            </li>
            <!-- Menu Footer-->
            <li class="user-footer">
                @*<div class="pull-left">
                        <a href="#" class="btn btn-default btn-flat">Perfil</a>
                    </div>*@
                <div class="pull-right">
                    @using (Html.BeginForm("LogOff", "Account", FormMethod.Post, new { id = "logoutForm" }))
                    {
                        @Html.AntiForgeryToken()
                        <a href="javascript:document.getElementById('logoutForm').submit()" class="btn btn-default btn-flat">Cerrar sesi&oacute;n</a>
                    }
                </div>
            </li>
        </ul>
    </li>
}

Sistema_Venta_Web/Views/Shared/_LayoutMinimal.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <!-- Enable compatibility -->
    <meta http-equiv="X-UA-Compatible" content="IE=edge;IE=10;IE=9" />
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" />
    <!-- Title of page -->
    <title>@ViewBag.Title</title>
    <!-- Icon application -->
    <link rel="icon" href="~/favicon.ico">
    <!-- Styles -->
    <link href="~/Content/lib/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/lib/font-awesome/css/font-awesome.min.css" rel="stylesheet" />
    <link href="~/Content/lib/bootstrap-datepicker/css/bootstrap-datepicker.min.css" rel="stylesheet" />
    <link href="~/Content/css/main.css" rel="stylesheet" />
    <link href="~/Content/css/skin-red.css" rel="stylesheet" />
    <script src="~/Content/lib/modernizr/js/modernizr-2.8.3.js"></script>
</head>
<body class="skin-red">
    <!-- Layout -->
    <div class="bsp-wrapper">
        <!-- Body -->
        <div class="bsp-body-wrapper">
            <!-- Header -->
            <div class="bsp-header">
                <div class="container-fluid">
                    <span class="bsp-brand">
                        @*<img src="~/Content/img/full_logo_withe_transparent_2.png" alt="Logo" />*@
                    </span>
                </div>
            </div>
            <!-- Content -->
            <div class="bsp-content">
                <div class="container-fluid" id="bodyMainContent">
                    @RenderBody()
                </div>
            </div>
            <!-- Footer -->
            <div class="bsp-footer">
                <div class="container-fluid">
                    <footer>
                        @*@(string.Format("{0} | {1} {2}", AppConfig.ApplicationCopyright, AppConfig.ApplicationShortName, AppConfig.ApplicationVersion))*@
                    </footer>
                </div>
            </div>
        </div>
    </div>
    <!-- Scripts -->
    <script src="~/Content/lib/jquery/js/jquery-3.3.1.min.js"></script>
    <script src="~/Content/lib/jquery/js/jquery.validate.min.js"></script>
    <script src="~/Content/lib/jquery/js/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/Content/lib/bootstrap/js/bootstrap.min.js"></script>
    <script src="~/Content/lib/bootstrap-datepicker/js/bootstrap-datepicker.min.js"></script>
    <script src="~/Content/lib/bootstrap-datepicker/js/bootstrap-datepicker.es.min.js"></script>
    <script type="text/javascript">
            var baseSiteUrl = '@Url.Content("~/")';
    </script>
    <script src="~/Content/js/app.js"></script>
    @RenderSection("scripts", required: false)
</body>

</html>

Sistema_Venta_Web/Views/Shared/_LayoutModals.cshtml
 <!-- Modal message -->
<div class="modal fade" id="modalMessage" tabindex="-1" role="dialog" aria-labelledby="titleModalMessage" aria-hidden="true">
    <div class="modal-dialog" role="document" id="dialogModalMessage">
        <div class="modal-content">
            <div class="modal-header">
                @*<button type="button" class="close" aria-label="Close" data-dismiss="modal"><span aria-hidden="true">&times;</span></button>*@
                <h4 class="modal-title" id="titleModalMessage"></h4>
            </div>
            <div class="modal-body" id="bodyModalMessage"></div>
            <div class="modal-footer" id="footerModalMessage">
                <button type="button" class="btn btn-outline pull-left" data-dismiss="modal" id="btnCancelModalMessage"></button>
                <button type="button" class="btn btn-outline" data-dismiss="modal" id="btnAcceptModalMessage"></button>
            </div>
        </div>
    </div>
</div>
<!-- Modal error -->
<div class="modal modal-danger fade" id="modalError" tabindex="-1" role="dialog" aria-labelledby="titleModalError" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document" id="dialogModalError">
        <div class="modal-content">
            <div class="modal-header pgm-message-danger" id="headerModalError">
                @*<button type="button" class="close" aria-label="Close" data-dismiss="modal"><span aria-hidden="true">&times;</span></button>*@
                <h4 class="modal-title" id="titleModalError">Error</h4>
            </div>
            <div class="modal-body" id="bodyModalError"></div>
            <div class="modal-footer" id="footerModalError">
                <button type="button" class="btn btn-outline pull-left" data-dismiss="modal" id="btnAceptarModalError">Aceptar</button>
            </div>
        </div>
    </div>
</div>
<!-- Modal loading  -->
<div class="modal fade" id="modalLoading" tabindex="-2" role="dialog" aria-labelledby="titleModalLoading" aria-hidden="true">
    <div class="bsp-loading" role="document">
        <i class="fa fa-refresh fa-spin fa-3x fa-fw" aria-hidden="true"></i><h4 id="messageLoading">Procesando, por favor espere...</h4>
    </div>
</div>

Sistema_Venta_Web/Views/Shared/_LayoutSideBar.cshtml
@using Microsoft.AspNet.Identity

@if (User.Identity.IsAuthenticated)
{
    //Obtenemos la lista con las opciones de menu y objeto.
    var opcMenu = AppConfig.MenuAplicacion;

    var listaMenuPadre = opcMenu.Where(x => x.CodigoOpcion == x.CodigoOpcionPadre && x.TipoOpcion == "Menu");

    <aside class="main-sidebar">
        <!-- sidebar: style can be found in sidebar.less -->
        <section class="sidebar" style="height:auto;">
            <!-- Sidebar Menu -->
            <ul class="sidebar-menu" data-widget="tree">
                <li class="header">MENU PRINCIPAL</li>
            </ul>
        </section>
    </aside>
}
else
{
    <aside class="main-sidebar">
        <!-- sidebar: style can be found in sidebar.less -->
        <section class="sidebar" style="height:auto;">
            <!-- Sidebar Menu -->
            <ul class="sidebar-menu" data-widget="tree">
                <li class="header">MENU PRINCIPAL</li>
                <!-- Optionally, you can add icons to the links -->
            </ul>
        </section>
    </aside>
}

Sistema_Venta_Web/Views/Shared/_LayoutSideBarControl.cshtml
<aside class="control-sidebar control-sidebar-dark">
    <!-- Create the tabs -->
    <ul class="nav nav-tabs nav-justified control-sidebar-tabs">
        <li class="active"><a href="#control-sidebar-home-tab" data-toggle="tab"><i class="fa fa-home"></i></a></li>
        <li><a href="#control-sidebar-settings-tab" data-toggle="tab"><i class="fa fa-gears"></i></a></li>
    </ul>
    <!-- Tab panes -->
    <div class="tab-content">
        <!-- Home tab content -->
        <div class="tab-pane active" id="control-sidebar-home-tab">
            <h3 class="control-sidebar-heading">Actividad Reciente</h3>
            <ul class="control-sidebar-menu">
                <li>
                    <a href="javascript:;">
                        <i class="menu-icon fa fa-birthday-cake bg-red"></i>
                        <div class="menu-info">
                            <h4 class="control-sidebar-subheading">Cena Navideña</h4>
                            <p>Celebrado el 2017-12-13</p>
                        </div>
                    </a>
                </li>
            </ul>
            <h3 class="control-sidebar-heading">Progreso de Tareas</h3>
            <ul class="control-sidebar-menu">
                <li>
                    <a href="javascript:;">
                        <h4 class="control-sidebar-subheading">
                            Maquetacion Web Agenda Comercial
                            <span class="pull-right-container">
                                <span class="label label-danger pull-right">70%</span>
                            </span>
                        </h4>
                        <div class="progress progress-xxs">
                            <div class="progress-bar progress-bar-danger" style="width: 70%"></div>
                        </div>
                    </a>
                </li>
            </ul>
        </div>
        <!-- Stats tab content -->
        <div class="tab-pane" id="control-sidebar-stats-tab">Configuracion Adicional</div>
        <!-- Settings tab content -->
        <div class="tab-pane" id="control-sidebar-settings-tab">
            <form method="post">
                <h3 class="control-sidebar-heading">Configuracion General</h3>
                <div class="form-group">
                    <label class="control-sidebar-subheading">
                        Acceso al menu Reportes
                        <input type="checkbox" class="pull-right" checked>
                    </label>
                    <p>
                        Activar o desactivar el acceso al menu de reportes
                    </p>
                </div>
            </form>
        </div>
    </div>
</aside>
<!-- Add the sidebar's background. This div must be placed
immediately after the control sidebar -->
<div class="control-sidebar-bg"></div>